import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { useDispatch, useSelector } from 'react-redux'

import styles from '../styles/Home.module.css'

import { emitGetGames, emitOpenGame, init } from '@/utils/socket'
import Instructions from '@/components/common/Instructions'

const inter = Inter({ subsets: ['latin'] })

export default function Start() {
  const [myGame, setMyGame] = useState('')

  const router = useRouter();
  const idGame = router.query.idGame;

  const { user, games } = useSelector((state) => ({ ...state }));
  const dispatch = useDispatch()

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token) {
      router.push('/login');
    }

    init(dispatch);
    emitGetGames()
    // obtener games
    const currentGame = localStorage.getItem('currentGame');
    if (currentGame) {
        setMyGame(currentGame);
    }  
  }, [])

  const openGame = () => {
    const idGame = Math.floor(Math.random() * 100000000);
    setMyGame(idGame);
    localStorage.setItem('currentGame', idGame)
    emitOpenGame(user.username, idGame);
  }

  const endGame = () => {
    /* localStorage.removeItem('currentGame')
    emitDeleteGame(user.username, myGame)
    setMyGame(''); */
  }

  const startGame = (idGame) => {
    router.push(`/${idGame}`)
  }

  const joinGame = (idGame) => {
    /* emitJoinGame(user.username, idGame);
    setMyGame(localStorage.setItem('currentGame', idGame));
    localStorage.setItem('state', 'playing')
    history(`/${idGame}`) */
  }

  return (
    <>
      <Head>
        <title>COUP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.start}>
        <Instructions position={'20px'} />
        <button
          onClick={openGame}
          className={styles.openButton}
          disabled={myGame}
        >
          Abrir Partida
        </button>
        <div className={styles.start__list}>
          {
            myGame ? (
              <div key={myGame} className={styles.container_games} style={{ borderBottom: '1px solid #2b2b2b' }}>
                <div className={styles.container__info}>
                  <h2>Tu Juego</h2>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column' }}>
                  <button onClick={() => startGame(myGame)} className={styles.btn_start}>Iniciar</button>
                  <button onClick={endGame} className={styles.btn_end}>Cancelar</button>
                </div>
              </div>
            ) : (
              ''
            )
          }

          {
            games.games && games.games.filter(game => game.idGame !== myGame).map((game, index) => (
              <div className={styles.container_games} key={index}>
                <div className={styles.container__info}>
                  <h2>{game.createdBy}</h2>
                </div>
                {
                  !myGame ? (
                    <button
                      onClick={() => joinGame(game.idGame)}
                      className={styles.btn_start}
                    >
                      Unirse
                    </button>
                  ) : ''
                }
              </div>
            ))
          }

        </div>
      </div>
    </>
  )
}
